name: build

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push docker image
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        docker build --tag ghcr.io/tgagor/grype --cache-from ghcr.io/tgagor/grype .
        docker run -i --rm ghcr.io/tgagor/grype version
        docker tag ghcr.io/tgagor/grype ghcr.io/tgagor/grype:alpine
        docker tag ghcr.io/tgagor/grype ghcr.io/tgagor/grype:${GITHUB_REF##*/}
        docker push ghcr.io/tgagor/grype:alpine
        docker push ghcr.io/tgagor/grype:${GITHUB_REF##*/}
